import type { AuditReport } from "@/lib/api/types";
import type { PaymentPlan } from "@/lib/api/types";

interface AuditReportProps {
  report: AuditReport;
  plan: PaymentPlan;
}

export function AuditReport({ report, plan }: AuditReportProps) {
  const approvedCount = report.transactions.length;
  const totalExecuted = report.transactions.reduce((sum, t) => sum + t.amount, 0);

  const blockedWallets = report.riskCheck.checks.whitelistCheck.blockedWallets ?? [];
  const blockedItems = plan.items.filter((item) =>
    blockedWallets.includes(item.recipient.walletAddress)
  );
  const blockedCount = blockedItems.length;
  const blockedAmount = blockedItems.reduce((sum, item) => sum + item.amount, 0);

  return (
    <section className="relative overflow-hidden rounded-xl border border-white/10 bg-slate-900/60 backdrop-blur-sm">
      <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-blue-500/20 to-transparent" />

      {/* Receipt header */}
      <div className="border-b border-white/10 bg-slate-950/50 px-5 py-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-blue-500/10 text-blue-400">
              <svg className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
            </div>
            <div>
              <h2 className="text-sm font-bold text-slate-100">Settlement Receipt</h2>
              <p className="text-[11px] text-slate-500">Generated by AgentCFO · {new Date(report.timestamp).toLocaleString("zh-CN")}</p>
            </div>
          </div>
          <span className="rounded-full border border-blue-500/20 bg-blue-500/10 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wider text-blue-400">
            Audit
          </span>
        </div>
      </div>

      <div className="p-5">
        <p className="text-sm text-slate-300">{report.summary}</p>

        {/* Stats grid */}
        <div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">
          <div className="rounded-xl border border-emerald-500/15 bg-emerald-500/5 px-3 py-4 text-center">
            <p className="text-2xl font-bold text-emerald-400">{approvedCount}</p>
            <p className="mt-1 text-[10px] font-medium uppercase tracking-wider text-emerald-400/70">Approved</p>
          </div>
          <div className="rounded-xl border border-red-500/15 bg-red-500/5 px-3 py-4 text-center">
            <p className="text-2xl font-bold text-red-400">{blockedCount}</p>
            <p className="mt-1 text-[10px] font-medium uppercase tracking-wider text-red-400/70">Blocked</p>
          </div>
          <div className="rounded-xl border border-white/10 bg-slate-950/50 px-3 py-4 text-center">
            <p className="text-2xl font-bold text-slate-100">{plan.totalAmount}</p>
            <p className="mt-1 text-[10px] font-medium uppercase tracking-wider text-slate-500">Planned (USDC)</p>
          </div>
          <div className="rounded-xl border border-blue-500/15 bg-blue-500/5 px-3 py-4 text-center">
            <p className="text-2xl font-bold text-blue-400">{totalExecuted}</p>
            <p className="mt-1 text-[10px] font-medium uppercase tracking-wider text-blue-400/70">Executed (USDC)</p>
          </div>
        </div>

        {/* Summary sections */}
        <div className="mt-5 space-y-2.5">
          <div className="flex items-start gap-3 rounded-lg border border-emerald-500/15 bg-emerald-500/5 px-4 py-3">
            <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-emerald-500/15 text-emerald-400">
              <svg className="h-3.5 w-3.5" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
            </div>
            <div>
              <p className="text-sm font-semibold text-emerald-300">Execution Summary</p>
              <p className="mt-0.5 text-[11px] leading-relaxed text-emerald-400/80">
                {approvedCount} simulated transactions processed on Base Sepolia testnet.
                All payouts verified against AgentCFO treasury policy.
              </p>
            </div>
          </div>

          <div className="flex items-start gap-3 rounded-lg border border-red-500/15 bg-red-500/5 px-4 py-3">
            <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-red-500/15 text-red-400">
              <svg className="h-3.5 w-3.5" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
              </svg>
            </div>
            <div>
              <p className="text-sm font-semibold text-red-300">Risk Summary</p>
              <p className="mt-0.5 text-[11px] leading-relaxed text-red-400/80">
                Whitelist check blocked {blockedCount} recipient{blockedCount > 1 ? "s" : ""}. {report.riskCheck.checks.whitelistCheck.reason}.
                Blocked amount: {blockedAmount} USDC. No funds were transferred for blocked items.
              </p>
            </div>
          </div>
        </div>

        {/* Receipt footer */}
        <div className="mt-5 border-t border-dashed border-white/10 pt-4">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-[10px] font-medium uppercase tracking-wider text-slate-600">Approved by</p>
              <p className="mt-0.5 text-sm font-medium text-slate-300">{report.approvedBy}</p>
            </div>
            <div className="text-right">
              <p className="text-[10px] font-medium uppercase tracking-wider text-slate-600">Permission boundary</p>
              <p className="mt-0.5 text-[11px] text-slate-400">budget:50 / singleLimit:25 / token:USDC</p>
            </div>
          </div>
        </div>

        {/* Mock disclaimer */}
        <div className="mt-4 rounded-lg border border-white/5 bg-slate-950/50 px-3 py-2.5">
          <p className="text-[11px] leading-relaxed text-slate-600">
            This is a mock settlement receipt for demonstration purposes.
            No real treasury operation or blockchain transaction occurred.
          </p>
        </div>
      </div>
    </section>
  );
}
