import type { AuditReport } from "@/lib/api/types";
import type { PaymentPlan } from "@/lib/api/types";

interface AuditReportProps {
  report: AuditReport;
  plan: PaymentPlan;
}

export function AuditReport({ report, plan }: AuditReportProps) {
  const approvedCount = report.transactions.length;
  const totalExecuted = report.transactions.reduce((sum, t) => sum + t.amount, 0);

  const blockedWallets = report.riskCheck.checks.whitelistCheck.blockedWallets ?? [];
  const blockedItems = plan.items.filter((item) =>
    blockedWallets.includes(item.recipient.walletAddress)
  );
  const blockedCount = blockedItems.length;
  const blockedAmount = blockedItems.reduce((sum, item) => sum + item.amount, 0);

  return (
    <section className="rounded-xl border border-slate-200 bg-white shadow-sm">
      {/* Receipt header */}
      <div className="rounded-t-xl border-b border-slate-100 bg-slate-50 px-6 py-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <svg className="h-5 w-5 text-blue-600" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            <div>
              <h2 className="text-sm font-bold text-slate-900">Settlement Receipt</h2>
              <p className="text-xs text-slate-500">Generated by AgentCFO · {new Date(report.timestamp).toLocaleString("zh-CN")}</p>
            </div>
          </div>
          <span className="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-semibold uppercase tracking-wider text-blue-700">
            Audit
          </span>
        </div>
      </div>

      <div className="p-6">
        <p className="text-sm text-slate-700">{report.summary}</p>

        {/* Stats grid */}
        <div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">
          <div className="rounded-lg border border-slate-100 bg-white px-3 py-3 text-center shadow-sm">
            <p className="text-xl font-bold text-emerald-700">{approvedCount}</p>
            <p className="mt-0.5 text-xs font-medium uppercase tracking-wider text-slate-500">Approved</p>
          </div>
          <div className="rounded-lg border border-slate-100 bg-white px-3 py-3 text-center shadow-sm">
            <p className="text-xl font-bold text-red-700">{blockedCount}</p>
            <p className="mt-0.5 text-xs font-medium uppercase tracking-wider text-slate-500">Blocked</p>
          </div>
          <div className="rounded-lg border border-slate-100 bg-white px-3 py-3 text-center shadow-sm">
            <p className="text-xl font-bold text-slate-900">{plan.totalAmount}</p>
            <p className="mt-0.5 text-xs font-medium uppercase tracking-wider text-slate-500">Planned (USDC)</p>
          </div>
          <div className="rounded-lg border border-slate-100 bg-white px-3 py-3 text-center shadow-sm">
            <p className="text-xl font-bold text-blue-700">{totalExecuted}</p>
            <p className="mt-0.5 text-xs font-medium uppercase tracking-wider text-slate-500">Executed (USDC)</p>
          </div>
        </div>

        {/* Summary sections */}
        <div className="mt-5 space-y-3">
          <div className="flex items-start gap-3 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3">
            <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-emerald-100">
              <svg className="h-4 w-4 text-emerald-600" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
            </div>
            <div>
              <p className="text-sm font-semibold text-emerald-900">Execution Summary</p>
              <p className="mt-0.5 text-xs leading-relaxed text-emerald-700">
                {approvedCount} simulated transactions processed on Base Sepolia testnet.
                All payouts verified against AgentCFO treasury policy.
              </p>
            </div>
          </div>

          <div className="flex items-start gap-3 rounded-lg border border-red-200 bg-red-50 px-4 py-3">
            <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-red-100">
              <svg className="h-4 w-4 text-red-600" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
              </svg>
            </div>
            <div>
              <p className="text-sm font-semibold text-red-900">Risk Summary</p>
              <p className="mt-0.5 text-xs leading-relaxed text-red-700">
                Whitelist check blocked {blockedCount} recipient{blockedCount > 1 ? "s" : ""}. {report.riskCheck.checks.whitelistCheck.reason}.
                Blocked amount: {blockedAmount} USDC. No funds were transferred for blocked items.
              </p>
            </div>
          </div>
        </div>

        {/* Receipt footer */}
        <div className="mt-5 border-t border-dashed border-slate-200 pt-4">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-xs font-medium uppercase tracking-wider text-slate-400">Approved by</p>
              <p className="text-sm font-medium text-slate-700">{report.approvedBy}</p>
            </div>
            <div className="text-right">
              <p className="text-xs font-medium uppercase tracking-wider text-slate-400">Permission boundary</p>
              <p className="text-xs text-slate-600">budget:50 / singleLimit:25 / token:USDC</p>
            </div>
          </div>
        </div>

        {/* Mock disclaimer */}
        <div className="mt-4 rounded-lg border border-slate-100 bg-slate-50 px-3 py-2.5">
          <p className="text-xs leading-relaxed text-slate-400">
            This is a mock settlement receipt for demonstration purposes.
            No real treasury operation or blockchain transaction occurred.
          </p>
        </div>
      </div>
    </section>
  );
}
