import type { AuditReport } from "@/lib/api/types";

interface AuditReportProps {
  report: AuditReport;
}

export function AuditReport({ report }: AuditReportProps) {
  const approvedCount = report.transactions.length;
  const totalPlanned = report.riskCheck.passed
    ? report.transactions.reduce((sum, t) => sum + t.amount, 0)
    : report.transactions.reduce((sum, t) => sum + t.amount, 0);
  // Bob was blocked (15 USDC), so total planned = executed + blocked
  const blockedAmount = 15;

  return (
    <section className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
      <div className="flex items-center justify-between">
        <h2 className="text-sm font-semibold uppercase tracking-wide text-slate-500">
          Audit Report
        </h2>
        <span className="text-xs text-slate-400">
          {new Date(report.timestamp).toLocaleString("zh-CN")}
        </span>
      </div>

      <p className="mt-2 text-sm text-slate-700">{report.summary}</p>

      <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">
        <div className="rounded-lg border border-slate-100 bg-slate-50 px-3 py-2 text-center">
          <p className="text-lg font-semibold text-slate-900">{approvedCount}</p>
          <p className="text-xs text-slate-500">Approved</p>
        </div>
        <div className="rounded-lg border border-slate-100 bg-slate-50 px-3 py-2 text-center">
          <p className="text-lg font-semibold text-red-700">1</p>
          <p className="text-xs text-slate-500">Blocked</p>
        </div>
        <div className="rounded-lg border border-slate-100 bg-slate-50 px-3 py-2 text-center">
          <p className="text-lg font-semibold text-slate-900">{totalPlanned + blockedAmount}</p>
          <p className="text-xs text-slate-500">Total Plan (USDC)</p>
        </div>
        <div className="rounded-lg border border-slate-100 bg-slate-50 px-3 py-2 text-center">
          <p className="text-lg font-semibold text-emerald-700">{totalPlanned}</p>
          <p className="text-xs text-slate-500">Executed (USDC)</p>
        </div>
      </div>

      <div className="mt-4 space-y-2">
        <div className="flex items-start gap-2 rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2">
          <svg className="mt-0.5 h-4 w-4 text-emerald-600" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          <div>
            <p className="text-xs font-medium text-emerald-900">Execution Summary</p>
            <p className="text-xs text-emerald-700">
              {approvedCount} simulated transactions on Base Sepolia testnet. All verified by AgentCFO policy.
            </p>
          </div>
        </div>

        <div className="flex items-start gap-2 rounded-lg border border-red-200 bg-red-50 px-3 py-2">
          <svg className="mt-0.5 h-4 w-4 text-red-600" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
          </svg>
          <div>
            <p className="text-xs font-medium text-red-900">Risk Summary</p>
            <p className="text-xs text-red-700">
              Whitelist check blocked 1 recipient ({report.riskCheck.checks.whitelistCheck.reason}).
              Blocked amount: {blockedAmount} USDC.
            </p>
          </div>
        </div>
      </div>

      <div className="mt-4 rounded-lg border border-slate-100 bg-slate-50 px-3 py-2">
        <p className="text-xs text-slate-500">
          <span className="font-medium text-slate-700">Generated by:</span> {report.approvedBy}
        </p>
        <p className="mt-1 text-xs text-slate-400">
          This is a mock audit report for demonstration purposes. No real treasury operation occurred.
        </p>
      </div>
    </section>
  );
}
